# Generated by Django 3.1.14 on 2022-01-16 16:59

from django.db import migrations


def exchange_title(apps, schema_editor):
    Pokemon = apps.get_model('pokemon_entities', 'Pokemon')
    Pokemon_change_title = apps.get_model('pokemon_entities', 'Pokemon_change_title')
    for pokemon in Pokemon.objects.all():
        Pokemon_change_title.objects.create(
            title_ru=pokemon.title,
            image=pokemon.image
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemon_change_title'),
    ]

    operations = [
        migrations.RunPython(exchange_title),
    ]
