# Generated by Django 3.1.14 on 2022-01-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20220116_2020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemon_change_title',
            new_name='Pokemon',
        ),
    ]
